<a href="https://colab.research.google.com/github/FridaOyucho/Viral-Load-Coverage-and-Suppression-Analysis/blob/main/VL_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
#Mount google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
#Identify the  PatientLabs File Path
'/content/drive/MyDrive/Care CT_PatientLabs.csv'

'/content/drive/MyDrive/Care CT_PatientLabs.csv'

In [5]:
#Identify the  FACTART File Path
'/content/drive/MyDrive/Linelist_FACTART/Linelist_FACTART.csv'

'/content/drive/MyDrive/Linelist_FACTART/Linelist_FACTART.csv'

In [8]:
#Loading ART data
#file_path = "/content/drive/MyDrive/Linelist_FACTART/Linelist_FACTART.csv"

#FactART = pd.read_csv(file_path)

#FactART.head()

In [9]:
#Load PatientLabs data
file_path = "/content/drive/MyDrive/Care CT_PatientLabs.csv"

PatientLabs = pd.read_csv(file_path)

PatientLabs.head()

/tmp/ipykernel_97780/813224867.py:5: DtypeWarning: Columns (0,9,11,16,22,23,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  PatientLabs = pd.read_csv(file_path)

,PatientID,PatientPk,FacilityID,SiteCode,FacilityName,SatelliteName,VisitID,OrderedbyDate,ReportedbyDate,TestName,...,PatientPKHash,PatientIDHash,ID,Reason,Date_Last_Modified,Date_Created,LoadDate,RecordUUID,voided,VoidingSource
0,1302319858,33181,NaN,13023,Kenyatta National Hospital,NaN,2484963,2024-10-18 00:00:00.000,2024-10-23 00:00:00.000,Viral Load,...,EA808805CD903924F3747B8A316D49A46380B36FA6EB30...,17662ACCC3F867E090C58E776589BCA047373CC7E1D5B7...,520E058A-12EF-45B2-862A-DEC80850A803,Routine,NaN,2024-10-25 00:05:05.000,2024-11-27 22:38:44.053,0395a2d4-9fe8-4d81-b0b8-d34215a61955,0,NaN
1,1302324031,49473,NaN,13023,Kenyatta National Hospital,NaN,2300030,2024-02-22 00:00:00.000,2024-02-26 00:00:00.000,Viral Load,...,2D396D412A4156FF5D22D419EABBCA15C49D309333D5A8...,9A1C31A69CB852FCDCC61A8A0633616339C54D14BDB26B...,2DAAE6C5-4B98-4A23-A53F-AC4C00495338,Routine,NaN,2024-02-27 00:02:04.000,2024-11-27 22:38:44.053,73081e6d-8fa8-422c-b7d4-610f587fa3d2,0,NaN
2,1302301505,2210,NaN,13023,Kenyatta National Hospital,NaN,2462464,2024-09-13 00:00:00.000,2024-09-25 00:00:00.000,Viral Load,...,FDA8ADA497B0F3FC20791888D9BB00D974F54D81D87EB7...,AA68CA045CFA6AFAA2F22AC3EB3C7981ACBD4EBCB58CEF...,2EFCF3B6-649B-4998-A7C0-FCFF8693DCE1,Routine,NaN,2024-09-26 00:05:06.000,2024-11-27 22:38:44.053,b4d58615-4594-476a-97cf-8b42cccb0e44,0,NaN
3,1302319838,33108,NaN,13023,Kenyatta National Hospital,NaN,2438892,2024-08-19 00:00:00.000,2024-08-23 00:00:00.000,Viral Load,...,CC9871647D474B4B4A91FAE135661E14944DA341142B37...,A5EC459149F1620222D34A28013D99E30E8723308D2529...,B40043F8-CA38-45CD-A518-832AC0A3F650,Routine,NaN,2024-08-24 00:05:03.000,2024-11-27 22:38:44.053,f72552e7-3a9f-45ab-859c-c98852b8e15a,0,NaN
4,1302304365,5050,NaN,13023,Kenyatta National Hospital,NaN,2470608,2024-09-27 00:00:00.000,2024-10-03 00:00:00.000,Viral Load,...,6CEE713F4EAE372D5DE35FE1BAFE9CFDD44D5BBB83601A...,63197B49A7818732BDF64EE87B25312FC0116E23E67695...,1B31EE39-8639-4F25-A8AE-22424DF83FEB,Routine,NaN,2024-10-07 00:05:03.000,2024-11-27 22:38:44.053,6e68ce91-320a-4e19-b4b9-a691a15672ec,0,NaN

Data Exploration

In [10]:
PatientLabs.shape

(4685976, 29)

In [11]:
print(PatientLabs.dtypes)

PatientID              object
PatientPk               int64
FacilityID            float64
SiteCode                int64
FacilityName           object
SatelliteName         float64
VisitID                 int64
OrderedbyDate          object
ReportedbyDate         object
TestName               object
EnrollmentTest        float64
TestResult             object
BaselineTest          float64
Emr                    object
Project                object
DateSampleTaken        object
SampleType             object
Processed             float64
Created               float64
PatientPKHash          object
PatientIDHash          object
ID                     object
Reason                 object
Date_Last_Modified     object
Date_Created           object
LoadDate               object
RecordUUID             object
voided                  int64
VoidingSource          object
dtype: object

In [39]:
#check missingness
print(PatientLabs.isnull().sum())

PatientID                   0
PatientPk                   0
FacilityID            4685976
SiteCode                    0
FacilityName             1699
SatelliteName         4685976
VisitID                     0
OrderedbyDate               0
ReportedbyDate              0
TestName               418149
EnrollmentTest        4685976
TestResult              18504
BaselineTest          4685976
Emr                         0
Project                     0
DateSampleTaken             0
SampleType            2400636
Processed             4685976
Created               4685976
PatientPKHash               0
PatientIDHash               0
ID                          0
Reason                2096290
Date_Last_Modified    4303790
Date_Created                0
LoadDate                    0
RecordUUID             209508
voided                      0
VoidingSource         4618254
dtype: int64

In [13]:
#Filter test name to VL
PatientLabs['TestName'].unique()

array(['Viral Load', 'CD4 Count', nan, 'Determine rapid test', 'Unigold',
       'CD4 Percentage', 'Sputum for Acid Fast Bacilli', 'Oraquick',
       'PCRq', 'GeneXpert', 'Serum Cryptococcal Ag',
       'Rapid Plasma Reagin',
       'Post-prandial blood glucose measurement (mg/dL)', 'ALT',
       'VDRL Titre',
       'Treponema Pallidum Hemagglutination Assay, Qualitative', 'TB LAM',
       'Tuberculosis', 'Rifampicin (R)', 'PCR', 'Isoniazid (H)',
       'Hemoglobin (HGB)', 'Serum creatinine (umol/L)', 'FLDEX1 - MON',
       'Hema', 'RVGM', 'LYM2', 'Eritro', 'MXD', 'PCT', 'RDWCV', 'MXD2',
       'Tryglicerid', 'Glycemia', 'FLDEX4 -MON2 %', 'PDW', 'HGM',
       'ColTot', 'UREA', 'BILD', 'Leuco', 'BLT', 'mpv', 'NEUT2', 'GOT',
       'Creatinine', 'GPT', 'CHGM', 'Hemo', 'LYM', 'HBA1C', 'ColHDL',
       'CD8%', 'FLDEX5 - EOS2 %', 'PLRC', 'AlfaAmilasi',
       'FLDEX2 - MON2 %', 'FLDEX3 - BAS', 'Plasmodium', 'CL', 'K', 'ALBU',
       'ALP', 'FLDEX6 - BAS2 %', 'CD4/CD8', 'PT', 'CD8',
       'Treponema Pallidum Hemagglutination Assay', 'NEUT', 'PLAQ'],
      dtype=object)

In [40]:
print(PatientLabs['TestName'].value_counts())

TestName
Viral Load                                   3784075
CD4 Count                                     151418
Serum creatinine (umol/L)                      43794
GeneXpert                                      17146
Hemoglobin (HGB)                               15552
                                              ...
PT                                                 2
CD8%                                               1
AlfaAmilasi                                        1
ALP                                                1
Treponema Pallidum Hemagglutination Assay          1
Name: count, Length: 69, dtype: int64

In [15]:
#Filter test name
PatientLabsVL = PatientLabs[PatientLabs['TestName'].str.contains('VIRAL', case=False, na=False)]

In [16]:
#Convert to datetime
PatientLabsVL['OrderedbyDate'] = pd.to_datetime(PatientLabsVL['OrderedbyDate'])
PatientLabsVL['DateSampleTaken'] = pd.to_datetime(PatientLabsVL['DateSampleTaken'])

/tmp/ipykernel_97780/450161685.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PatientLabsVL['OrderedbyDate'] = pd.to_datetime(PatientLabsVL['OrderedbyDate'])
/tmp/ipykernel_97780/450161685.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PatientLabsVL['DateSampleTaken'] = pd.to_datetime(PatientLabsVL['DateSampleTaken'])

In [17]:
# Get min and max dates
print("Earliest date:", PatientLabs['OrderedbyDate'].min())
print("Latest date:", PatientLabs['OrderedbyDate'].max())

Earliest date: 2024-01-01 00:00:00.000
Latest date: 2026-09-20 00:00:00.000

In [18]:
#filter dates to August 2026
PatientLabsVL_filtered = PatientLabsVL[
    (PatientLabsVL['OrderedbyDate'] >= '2024-01-01') &
    (PatientLabsVL['OrderedbyDate'] <= '2026-08-31')
    ]
PatientLabsVL_filtered.shape

(3783598, 29)

In [19]:
#Confirm all dates are between Jan 2024 through August 2026
PatientLabsVL_filtered [['OrderedbyDate']].agg(['min', 'max'])

               OrderedbyDate
min  2024-01-01 00:00:00.000
max  2026-09-20 00:00:00.000

In [21]:
#Filter the data to only required variables
VLData = PatientLabsVL_filtered[
    ['PatientPKHash',
     'SiteCode',
     'TestName',
     'OrderedbyDate',
     'TestResult',
     'DateSampleTaken',
     'SampleType']
                                ]
VLData.shape

(3783598, 7)

In [22]:
#UniqueID. Concat PatientPKHash with SiteCode
VLData['UniqueID'] = (VLData['PatientPKHash'].astype(str) +

VLData['SiteCode'].astype(str)
)


#Make UniqueID first col
cols = ['UniqueID'] + [c for c in VLData.columns if c != 'UniqueID']
VLData = VLData[cols]

/tmp/ipykernel_97780/3688661146.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  VLData['UniqueID'] = (VLData['PatientPKHash'].astype(str) +

In [23]:
VLData

,UniqueID,PatientPKHash,SiteCode,TestName,OrderedbyDate,TestResult,DateSampleTaken,SampleType
0,EA808805CD903924F3747B8A316D49A46380B36FA6EB30...,EA808805CD903924F3747B8A316D49A46380B36FA6EB30...,13023,Viral Load,2024-10-18,LDL,2024-10-18,NaN
1,2D396D412A4156FF5D22D419EABBCA15C49D309333D5A8...,2D396D412A4156FF5D22D419EABBCA15C49D309333D5A8...,13023,Viral Load,2024-02-22,LDL,2024-02-22,NaN
2,FDA8ADA497B0F3FC20791888D9BB00D974F54D81D87EB7...,FDA8ADA497B0F3FC20791888D9BB00D974F54D81D87EB7...,13023,Viral Load,2024-09-13,LDL,2024-09-13,NaN
3,CC9871647D474B4B4A91FAE135661E14944DA341142B37...,CC9871647D474B4B4A91FAE135661E14944DA341142B37...,13023,Viral Load,2024-08-19,LDL,2024-08-19,NaN
4,6CEE713F4EAE372D5DE35FE1BAFE9CFDD44D5BBB83601A...,6CEE713F4EAE372D5DE35FE1BAFE9CFDD44D5BBB83601A...,13023,Viral Load,2024-09-27,LDL,2024-09-27,NaN
...,...,...,...,...,...,...,...,...
4685971,1A10BCA49FFD188E60E252AA6B7B845CCD9F33845328E0...,1A10BCA49FFD188E60E252AA6B7B845CCD9F33845328E0...,15204,Viral Load,2026-03-27,0,1900-01-01,NaN
4685972,28535CA9EC2C55EBE3BD3A6F46BA906A53A6ABEA791034...,28535CA9EC2C55EBE3BD3A6F46BA906A53A6ABEA791034...,15204,Viral Load,2026-06-23,0,1900-01-01,NaN
4685973,82D31660EE7CB7F0561C347838DC47D63A2060E901277F...,82D31660EE7CB7F0561C347838DC47D63A2060E901277F...,15204,Viral Load,2026-04-28,0,1900-01-01,NaN
4685974,614DBE23AA2695E60167E2BEC4D56CEECAA930A00B3781...,614DBE23AA2695E60167E2BEC4D56CEECAA930A00B3781...,15204,Viral Load,2026-01-09,0,1900-01-01,NaN
4685975,356E22C995D7F6BC6D55080CB91343FA60AB6B6C8459AB...,356E22C995D7F6BC6D55080CB91343FA60AB6B6C8459AB...,15204,Viral Load,2026-01-19,0,1900-01-01,NaN

In [24]:
#identify numerical and non-numerical values
total = len(VLData)
numeric = pd.to_numeric(VLData['TestResult'], errors='coerce').notna().sum()
non_numeric = pd.to_numeric(VLData['TestResult'], errors='coerce').isna().sum()

print(f"Total: {total:,}")
print(f"Numeric: {numeric:,}")
print(f"Non-numeric: {non_numeric:,}")

Total: 3,783,598
Numeric: 3,034,870
Non-numeric: 748,728

In [25]:
#Tabulate test results
VLData.loc[
    pd.to_numeric(VLData['TestResult'], errors='coerce').isna(),
    'TestResult'
].value_counts()

TestResult
LDL                        743433
DETECTED                     2775
BEYOND DETECTABLE LIMIT      2272
POOR SAMPLE QUALITY           139
Invalid                        52
Collect New Sample             43
> 10000000                      4
collect another sample          3
Rejected                        2
>10000000                       2
ND                              1
Colllect New Sample             1
<20 cps/ml                      1
Name: count, dtype: int64

In [27]:
# Standardize and map to the correct values
VLData['TestResult2'] = (
    VLData['TestResult']
    .astype(str)
    .str.strip()
)

# Mapping rules
mapping = {
    'Undetectable': 0,
    'Not detected': 0,
    'NOT DETECTED': 0,
    'Trget Not Detected': 0,
    'Target Not Detected.': 0,
    'ND': 0,
    'No': 0,
    'LDL': 49,
    '<LDL': 49,
    '< 40': 39,
    '<40': 39,
    '> 10000000': 10000000,
    'Rejected': np.nan,
    'Invalid': np.nan,
    'INVALID': np.nan,
    'Yes': np.nan,
    'Failed': np.nan,
    'Detected': np.nan,
    'Detected DBS': np.nan,
    'POOR SAMPLE QUALITY': np.nan,
    'Collect New Sample': np.nan,
    'BEYOND DETECTABLE LIMIT': 0,
    '-1': np.nan,
    '': np.nan
}
# Apply mappings
VLData['TestResult2'] = VLData['TestResult2'].replace(mapping)

# Convert everything else to numeric
VLData['TestResult2'] = pd.to_numeric(
    VLData['TestResult2'],
    errors='coerce'
)

Identify Each Client’s Most Recent Viral Load

In [29]:
#Sort records by OrderedByDate in descending order within each client.
VLData = VLData.sort_values(
    by=['UniqueID', 'OrderedbyDate'],
    ascending=[True, False]
)

In [31]:
#Recent VL
# Remove records with missing dates
VLData = VLData.dropna(subset=['OrderedbyDate'])

# Get most recent VL per client
MostRecentVL = VLData.loc[
    VLData.groupby('UniqueID')['OrderedbyDate'].idxmax()
].copy()

# Sort
MostRecentVL = MostRecentVL.sort_values('OrderedbyDate', ascending=False)

print(MostRecentVL.shape)

(1448509, 9)

In [35]:
#MostRecentVL.head(20)

In [37]:
#Save and download the dataset
MostRecentVL.to_csv(
    '/content/drive/MyDrive/Latest_Viral_Load_Per_Client.csv',
    index=False
)